In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv("creditcard.csv")[:80_000]
df.head(3)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0

In [33]:
X = df.drop(columns=['Time','Amount','Class']).values
y=df['Class'].values
f"Shapes of X={X.shape} y={y.shape}, #Fraud Cases={y.sum()}"

'Shapes of X=(80000, 28) y=(80000,), #Fraud Cases=196'

In [34]:
from sklearn.linear_model import LogisticRegression

mod = LogisticRegression(max_iter=1000)
mod.fit(X,y).predict(X).sum()

np.int64(151)

In [35]:
from sklearn.linear_model import LogisticRegression

mod = LogisticRegression(class_weight={0:1,1:2},max_iter=1000)
mod.fit(X,y).predict(X).sum()

np.int64(172)

In [36]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import precision_score, recall_score, make_scorer

# Define model
model = LogisticRegression(max_iter=1000)

# Parameter grid
param_grid = {
    'class_weight': [{0: 1, 1: v} for v in range(1, 4)]
}

# Scoring metrics
scoring = {
    'precision': make_scorer(precision_score),
    'recall': make_scorer(recall_score)
}

# GridSearchCV
grid = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    scoring=scoring,
    refit='precision',   # metric used to select best model
    cv=4,
    n_jobs=-1
)

# Fit
grid.fit(X, y)

GridSearchCV(cv=4, estimator=LogisticRegression(max_iter=1000), n_jobs=-1,
             param_grid={'class_weight': [{0: 1, 1: 1}, {0: 1, 1: 2},
                                          {0: 1, 1: 3}]},
             refit='precision',
             scoring={'precision': make_scorer(precision_score, response_method='predict'),
                      'recall': make_scorer(recall_score, response_method='predict')})

In [37]:
pd.DataFrame(grid.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_class_weight,params,split0_test_precision,split1_test_precision,split2_test_precision,split3_test_precision,mean_test_precision,std_test_precision,rank_test_precision,split0_test_recall,split1_test_recall,split2_test_recall,split3_test_recall,mean_test_recall,std_test_recall,rank_test_recall
0,0.356456,0.076411,0.011297,0.004015,"{0: 1, 1: 1}","{'class_weight': {0: 1, 1: 1}}",0.015071,1.0,0.975610,0.875000,0.716420,0.407626,1,0.979592,0.326531,0.816327,0.142857,0.566327,0.342825,3
1,0.331077,0.062554,0.012492,0.003105,"{0: 1, 1: 2}","{'class_weight': {0: 1, 1: 2}}",0.013090,1.0,0.977273,0.857143,0.711876,0.407080,2,0.979592,0.346939,0.877551,0.244898,0.612245,0.320415,2
2,0.383839,0.060223,0.009585,0.004079,"{0: 1, 1: 3}","{'class_weight': {0: 1, 1: 3}}",0.008179,1.0,0.955556,0.800000,0.690934,0.401122,3,0.979592,0.367347,0.877551,0.326531,0.637755,0.293401,1

In [38]:
from sklearn.metrics import precision_score, recall_score

recall_score(y,grid.predict(X))

0.6020408163265306

In [39]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import precision_score, recall_score, make_scorer

grid = GridSearchCV(
    estimator = LogisticRegression(max_iter=1000),
    param_grid={'class_weight':[{0:1 , 1:v} for v in np.linspace(1,20,30)]},
    scoring={'precision':make_scorer(precision_score),'recall':make_scorer(recall_score)},
    refit='precision',
    return_train_score=True,
    cv=10,
    n_jobs=-1
)
grid.fit(X,y);

In [43]:
plt.figure(figsize=(12,4))
df=pd.DataFrame(grid.cv_results_)
for score in['mean_test_recall','mean_test_precision']:
    plt.plot([_[1] for _in df['param_contamination']],
              df_results[score],
              label=score)
plt.legend();

SyntaxError: 'in' expected after for-loop variables (4038141156.py, line 4)